# Generated by Django 6.0.3 on 2026-03-05 11:32

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2026, 3, 5, 11, 32, 16, 311397, tzinfo=datetime.timezone.utc)), ('status', 'pending')), fields=('tenant', 'email'), name='unique_pending_invitation_per_tenant_email'),
        ),
    ]
