# Generated by Django 5.2.7 on 2026-04-09 01:28

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('camera_type', models.CharField(choices=[('backyard', 'Backyard'), ('front_door', 'Front Door'), ('bedroom', 'Bedroom'), ('garage', 'Garage'), ('living_room', 'Living Room'), ('other', 'Other')], default='other', max_length=20)),
                ('source_type', models.CharField(choices=[('registered', 'Registered'), ('webcam', 'Webcam')], default='registered', max_length=20)),
                ('rtsp_url', models.CharField(blank=True, max_length=512)),
                ('ai_camera_id', models.CharField(blank=True, default='', help_text='Identifier used by the AI module for this camera', max_length=200)),
                ('stream_path', models.CharField(blank=True, default='', help_text='Stable camera stream identifier used for UI/AI mapping', max_length=200)),
                ('min_confidence', models.FloatField(default=0.35, help_text='Detection confidence threshold 0-1')),
                ('min_bbox_area', models.IntegerField(default=400, help_text='Min bounding box area in pixels')),
                ('k_of_n_k', models.IntegerField(default=3, help_text='K-of-N persistence: require K')),
                ('k_of_n_n', models.IntegerField(default=5, help_text='K-of-N persistence: out of N')),
                ('cooldown_s', models.IntegerField(default=45, help_text='Alert cooldown seconds')),
                ('enabled_lanes', models.JSONField(blank=True, default=api.models.Camera._default_lanes, help_text="Active detection lanes (e.g. ['rt_detr', 'person_zone', 'fire_smoke_yolo'])")),
                ('source_kind', models.CharField(blank=True, default='', help_text='Derived or explicit source kind (e.g., rtsp, mjpeg, hls)', max_length=50)),
                ('source_fingerprint', models.CharField(blank=True, default='', help_text='Optional TLS fingerprint for HTTPS IP cameras', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('plan', models.CharField(default='free', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('robbery', 'Robbery'), ('stranger', 'Stranger'), ('fire', 'Fire'), ('intrusion', 'Intrusion'), ('other', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=24)),
                ('severity', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('media_key', models.CharField(blank=True, max_length=512)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='api.camera')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('instant_notification_levels', models.JSONField(blank=True, default=api.models.default_instant_notification_levels)),
                ('alert_sensitivity', models.CharField(default='medium', max_length=16)),
                ('data_retention_days', models.IntegerField(default=60)),
                ('audio_detection', models.BooleanField(default=True)),
                ('blur_faces', models.BooleanField(default=True)),
                ('consent_required', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='["a@b.com"]')),
                ('fcm_tokens', models.JSONField(blank=True, default=list, help_text='FCM device tokens')),
                ('severity_threshold', models.CharField(choices=[('high', 'High only (sev >= 4)'), ('medium', 'Medium & High (sev >= 3)'), ('all', 'All severities')], default='high', max_length=10)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnownEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('person', 'Person'), ('pet', 'Pet'), ('vehicle', 'Vehicle')], default='person', max_length=20)),
                ('group', models.CharField(choices=[('household', 'Household'), ('neighbor', 'Neighbor')], default='household', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ai_entity_id', models.CharField(blank=True, default='', help_text='Identifier returned by the AI module after enrollment', max_length=200)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=512)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('cameras', models.ManyToManyField(blank=True, related_name='known_entities', to='api.camera')),
                ('last_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_entities', to='api.camera')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='api.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantRuntimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webcam_enabled', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_settings', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_name', models.CharField(default='restricted', max_length=100)),
                ('zone_type', models.CharField(choices=[('restricted', 'Restricted'), ('monitor', 'Monitor')], default='restricted', max_length=20)),
                ('polygon_points', models.JSONField(default=list, help_text='List of [x,y] normalised coords')),
                ('enabled', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.camera')),
            ],
            options={
                'unique_together': {('camera', 'zone_name')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(default='email', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.incident')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_alert_user_id_9ddbfb_idx'), models.Index(fields=['user', 'delivered_at'], name='api_alert_user_id_0138ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source', models.CharField(choices=[('redis', 'Redis'), ('webhook', 'Webhook')], max_length=16)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_receipts', to='api.incident')),
            ],
            options={
                'indexes': [models.Index(fields=['event_id'], name='api_inciden_event_i_86c8b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'status'], name='api_invitat_email_d3bd82_idx'), models.Index(fields=['tenant', 'status'], name='api_invitat_tenant__9af9e6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant', 'email'), name='unique_pending_invitation_per_tenant_email')],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='api.camera')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='api.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'camera', 'ts'], name='api_detecti_tenant__13ffdc_idx')],
            },
        ),
    ]
