# Generated by Django 5.2.7 on 2026-04-18 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_postgres_bootstrap_objects(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE SCHEMA IF NOT EXISTS ops")
        cursor.execute("CREATE SCHEMA IF NOT EXISTS routing")
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION ops.bootstrap_system_defaults() RETURNS void
            LANGUAGE plpgsql
            AS $$
            BEGIN
                INSERT INTO api_projectionwatermark (
                    projection_name,
                    scope_type,
                    scope_id,
                    version,
                    last_event_id,
                    updated_at
                )
                VALUES
                    ('route_projection', 'global', '', 1, '', NOW()),
                    ('camera_context', 'global', '', 1, '', NOW())
                ON CONFLICT (projection_name, scope_type, scope_id) DO NOTHING;

                INSERT INTO api_schemabootstrapstate (key, value, updated_at)
                VALUES ('bootstrap.system_defaults.v1', '{}'::jsonb, NOW())
                ON CONFLICT (key)
                DO UPDATE SET updated_at = EXCLUDED.updated_at;
            END;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION ops.ensure_tenant_defaults(p_tenant_id bigint) RETURNS void
            LANGUAGE plpgsql
            AS $$
            BEGIN
                INSERT INTO api_notificationchannel (
                    created_at,
                    updated_at,
                    email_enabled,
                    push_enabled,
                    email_recipients,
                    fcm_tokens,
                    severity_threshold,
                    tenant_id
                )
                VALUES (
                    NOW(),
                    NOW(),
                    FALSE,
                    FALSE,
                    '[]'::jsonb,
                    '[]'::jsonb,
                    'high',
                    p_tenant_id
                )
                ON CONFLICT (tenant_id) DO NOTHING;

                INSERT INTO api_tenantruntimesetting (
                    created_at,
                    updated_at,
                    webcam_enabled,
                    tenant_id
                )
                VALUES (NOW(), NOW(), FALSE, p_tenant_id)
                ON CONFLICT (tenant_id) DO NOTHING;
            END;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION ops.ensure_camera_sidecars(p_camera_id bigint) RETURNS void
            LANGUAGE plpgsql
            AS $$
            BEGIN
                INSERT INTO api_airuntimeregistration (
                    created_at,
                    updated_at,
                    desired_enabled,
                    desired_ingest_backend,
                    desired_sample_hz,
                    desired_lanes,
                    desired_policy_version,
                    observed_ingest_backend,
                    observed_lanes,
                    source_metadata,
                    last_error,
                    camera_id
                )
                SELECT
                    NOW(),
                    NOW(),
                    c.status = 'active',
                    'opencv',
                    2.0,
                    COALESCE(c.enabled_lanes, '[]'::jsonb),
                    1,
                    '',
                    '[]'::jsonb,
                    '{}'::jsonb,
                    '',
                    c.id
                FROM api_camera c
                WHERE c.id = p_camera_id
                ON CONFLICT (camera_id) DO NOTHING;

                INSERT INTO api_mediamtxdesiredpath (
                    created_at,
                    updated_at,
                    stream_path,
                    desired_enabled,
                    relay_mode,
                    source_uri,
                    source_kind,
                    transcode_required,
                    preview_consumer_uri,
                    ai_consumer_uri,
                    evidence_consumer_uri,
                    path_generation,
                    drift_detected,
                    last_error,
                    camera_id
                )
                SELECT
                    NOW(),
                    NOW(),
                    COALESCE(NULLIF(c.stream_path, ''), NULLIF(c.ai_camera_id, ''), 'camera-' || c.id::text),
                    c.status = 'active',
                    'relay_only',
                    COALESCE(c.rtsp_url, ''),
                    COALESCE(c.source_kind, ''),
                    FALSE,
                    '',
                    '',
                    '',
                    1,
                    FALSE,
                    '',
                    c.id
                FROM api_camera c
                WHERE c.id = p_camera_id
                ON CONFLICT (camera_id) DO NOTHING;
            END;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION routing.bump_policy_version(
                p_tenant_id bigint,
                p_community_id bigint DEFAULT NULL
            ) RETURNS bigint
            LANGUAGE plpgsql
            AS $$
            DECLARE
                v_scope_type text;
                v_scope_id text;
                v_new_version bigint;
            BEGIN
                IF p_community_id IS NULL THEN
                    v_scope_type := 'tenant';
                    v_scope_id := p_tenant_id::text;
                ELSE
                    v_scope_type := 'community';
                    v_scope_id := p_community_id::text;
                END IF;

                INSERT INTO api_projectionwatermark (
                    projection_name,
                    scope_type,
                    scope_id,
                    version,
                    last_event_id,
                    updated_at
                )
                VALUES ('route_projection', v_scope_type, v_scope_id, 1, '', NOW())
                ON CONFLICT (projection_name, scope_type, scope_id)
                DO UPDATE SET
                    version = api_projectionwatermark.version + 1,
                    updated_at = NOW()
                RETURNING version INTO v_new_version;

                RETURN v_new_version;
            END;
            $$;
            """
        )

        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION routing.request_projection_rebuild(
                p_scope_type text,
                p_scope_id bigint,
                p_reason text
            ) RETURNS void
            LANGUAGE plpgsql
            AS $$
            BEGIN
                INSERT INTO api_projectionrepairrequest (
                    projection_name,
                    scope_type,
                    scope_id,
                    reason,
                    status,
                    requested_at
                )
                VALUES (
                    'route_projection',
                    COALESCE(NULLIF(p_scope_type, ''), 'tenant'),
                    COALESCE(p_scope_id::text, ''),
                    COALESCE(p_reason, ''),
                    'pending',
                    NOW()
                );
            END;
            $$;
            """
        )


def drop_postgres_bootstrap_objects(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP FUNCTION IF EXISTS routing.request_projection_rebuild(text, bigint, text)")
        cursor.execute("DROP FUNCTION IF EXISTS routing.bump_policy_version(bigint, bigint)")
        cursor.execute("DROP FUNCTION IF EXISTS ops.ensure_camera_sidecars(bigint)")
        cursor.execute("DROP FUNCTION IF EXISTS ops.ensure_tenant_defaults(bigint)")
        cursor.execute("DROP FUNCTION IF EXISTS ops.bootstrap_system_defaults()")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('last_token', models.CharField(blank=True, default='', max_length=256)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaBootstrapState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaMTXDesiredPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stream_path', models.CharField(max_length=200, unique=True)),
                ('desired_enabled', models.BooleanField(default=True)),
                ('relay_mode', models.CharField(choices=[('relay_only', 'Relay only'), ('remux', 'Remux'), ('transcode', 'Transcode')], default='relay_only', max_length=24)),
                ('source_uri', models.CharField(blank=True, default='', max_length=1024)),
                ('source_kind', models.CharField(blank=True, default='', max_length=64)),
                ('transcode_required', models.BooleanField(default=False)),
                ('preview_consumer_uri', models.CharField(blank=True, default='', max_length=1024)),
                ('ai_consumer_uri', models.CharField(blank=True, default='', max_length=1024)),
                ('evidence_consumer_uri', models.CharField(blank=True, default='', max_length=1024)),
                ('path_generation', models.BigIntegerField(default=1)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('drift_detected', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediamtx_desired_path', to='api.camera')),
            ],
        ),
        migrations.CreateModel(
            name='MediaMTXObservedPathState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_enabled', models.BooleanField(blank=True, null=True)),
                ('observed_source', models.CharField(blank=True, default='', max_length=1024)),
                ('observed_payload', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('desired_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observed_state', to='api.mediamtxdesiredpath')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attempts', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['published_at', 'created_at'], name='api_outboxe_publish_f27185_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='api_outboxe_aggrega_be88c4_idx'), models.Index(fields=['event_type', 'created_at'], name='api_outboxe_event_t_3f4608_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectionRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_name', models.CharField(default='route_projection', max_length=64)),
                ('scope_type', models.CharField(max_length=64)),
                ('scope_id', models.CharField(max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_name', models.CharField(max_length=64)),
                ('scope_type', models.CharField(default='global', max_length=32)),
                ('scope_id', models.CharField(blank=True, default='', max_length=128)),
                ('version', models.BigIntegerField(default=0)),
                ('last_event_id', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['projection_name', 'updated_at'], name='api_project_project_93dfca_idx')],
                'constraints': [models.UniqueConstraint(fields=('projection_name', 'scope_type', 'scope_id'), name='uq_projection_watermark_scope')],
            },
        ),
        migrations.CreateModel(
            name='ServiceWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_id', models.CharField(max_length=64, unique=True)),
                ('url', models.CharField(max_length=1024)),
                ('events', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivery_stats', models.JSONField(blank=True, default=dict)),
                ('has_secret', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('backend', 'Backend')], default='ai', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_webhooks', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AIRuntimeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desired_enabled', models.BooleanField(default=True)),
                ('desired_ingest_backend', models.CharField(default='opencv', max_length=64)),
                ('desired_sample_hz', models.FloatField(default=2.0)),
                ('desired_lanes', models.JSONField(blank=True, default=list)),
                ('desired_policy_version', models.IntegerField(default=1)),
                ('observed_enabled', models.BooleanField(blank=True, null=True)),
                ('observed_ingest_backend', models.CharField(blank=True, default='', max_length=64)),
                ('observed_sample_hz', models.FloatField(blank=True, null=True)),
                ('observed_lanes', models.JSONField(blank=True, default=list)),
                ('observed_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_registration', to='api.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['desired_enabled'], name='api_airunti_desired_69a9ee_idx'), models.Index(fields=['observed_last_seen_at'], name='api_airunti_observe_5e8f91_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediamtxdesiredpath',
            index=models.Index(fields=['desired_enabled'], name='api_mediamt_desired_e46b80_idx'),
        ),
        migrations.AddIndex(
            model_name='mediamtxdesiredpath',
            index=models.Index(fields=['last_reconciled_at'], name='api_mediamt_last_re_0870f5_idx'),
        ),
        migrations.AddIndex(
            model_name='mediamtxdesiredpath',
            index=models.Index(fields=['drift_detected'], name='api_mediamt_drift_d_0d27e6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediamtxobservedpathstate',
            index=models.Index(fields=['observed_at'], name='api_mediamt_observe_e78983_idx'),
        ),
        migrations.AddIndex(
            model_name='mediamtxobservedpathstate',
            index=models.Index(fields=['observed_enabled'], name='api_mediamt_observe_8dad62_idx'),
        ),
        migrations.AddIndex(
            model_name='projectionrepairrequest',
            index=models.Index(fields=['status', 'requested_at'], name='api_project_status_3e74b2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectionrepairrequest',
            index=models.Index(fields=['projection_name', 'scope_type', 'scope_id'], name='api_project_project_369fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='servicewebhook',
            index=models.Index(fields=['tenant', 'active'], name='api_service_tenant__730edd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicewebhook',
            index=models.Index(fields=['source', 'active'], name='api_service_source_c08b0a_idx'),
        ),
        migrations.RunPython(
            code=create_postgres_bootstrap_objects,
            reverse_code=drop_postgres_bootstrap_objects,
        ),
    ]
