# Generated by Django 4.2.2 on 2026-03-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invitation_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='unique_pending_invitation_per_tenant_email',
        ),
        migrations.AddField(
            model_name='camera',
            name='ai_camera_id',
            field=models.CharField(blank=True, default='', help_text='Identifier used by the AI module for this camera', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant', 'email'), name='unique_pending_invitation_per_tenant_email'),
        ),
    ]
