# Generated by Django 5.2.7 on 2026-04-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_knownentityembedding_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knownentity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='detection_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='embedding_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='entity_detection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='knownentity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='knownentity',
            index=models.Index(fields=['tenant', 'status'], name='api_knownen_tenant__7e7e73_idx'),
        ),
        migrations.AddIndex(
            model_name='knownentity',
            index=models.Index(fields=['tenant', 'detection_enabled'], name='api_knownen_tenant__8c3134_idx'),
        ),
    ]
