# Generated by Django 5.2.12 on 2026-03-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_invitation_unique_pending_invitation_per_tenant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_sensitivity',
            field=models.CharField(default='medium', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='audio_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='blur_faces',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='consent_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_retention_days',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
    ]
