# Generated by Django 5.2.7 on 2026-04-20 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_knownentity_created_by_knownentity_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownEntityAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('enrollment_image', 'Enrollment image'), ('thumbnail', 'Thumbnail')], default='enrollment_image', max_length=32)),
                ('file', models.FileField(upload_to='entity_assets/%Y/%m/%d')),
                ('storage_uri', models.CharField(blank=True, default='', max_length=1024)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.knownentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_assets', to='api.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_entity_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'entity', 'asset_type', 'is_active'], name='api_knownen_tenant__17d876_idx'), models.Index(fields=['tenant', 'is_active'], name='api_knownen_tenant__0dd362_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnownEntityProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='api.knownentity')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_processing_jobs', to='api.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='api_knownen_tenant__94e021_idx'), models.Index(fields=['entity', 'status', 'created_at'], name='api_knownen_entity__178349_idx')],
            },
        ),
    ]
