# Generated by Django 5.2.12 on 2026-03-07 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_alert_sensitivity_profile_audio_detection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('person', 'Person'), ('pet', 'Pet'), ('vehicle', 'Vehicle')], default='person', max_length=20)),
                ('group', models.CharField(choices=[('household', 'Household'), ('neighbor', 'Neighbor'), ('watchlist', 'Watchlist')], default='household', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ai_entity_id', models.CharField(blank=True, default='', help_text='Identifier returned by the AI module after enrollment', max_length=200)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=512)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
