# Generated by Django 5.2.7 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_knownentityasset_knownentityprocessingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="entity_detection_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable identity matching lane for this camera",
            ),
        ),
        migrations.AddField(
            model_name="tenantruntimesetting",
            name="identity_runtime_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
