# Generated by Django 5.2.7 on 2026-03-09 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_knownentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('backyard', 'Backyard'), ('front_door', 'Front Door'), ('bedroom', 'Bedroom'), ('garage', 'Garage'), ('living_room', 'Living Room'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='cooldown_s',
            field=models.IntegerField(default=45, help_text='Alert cooldown seconds'),
        ),
        migrations.AddField(
            model_name='camera',
            name='k_of_n_k',
            field=models.IntegerField(default=3, help_text='K-of-N persistence: require K'),
        ),
        migrations.AddField(
            model_name='camera',
            name='k_of_n_n',
            field=models.IntegerField(default=5, help_text='K-of-N persistence: out of N'),
        ),
        migrations.AddField(
            model_name='camera',
            name='min_bbox_area',
            field=models.IntegerField(default=400, help_text='Min bounding box area in pixels'),
        ),
        migrations.AddField(
            model_name='camera',
            name='min_confidence',
            field=models.FloatField(default=0.35, help_text='Detection confidence threshold 0-1'),
        ),
        migrations.AlterField(
            model_name='knownentity',
            name='group',
            field=models.CharField(choices=[('household', 'Household'), ('neighbor', 'Neighbor')], default='household', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='["a@b.com"]')),
                ('fcm_tokens', models.JSONField(blank=True, default=list, help_text='FCM device tokens')),
                ('severity_threshold', models.CharField(choices=[('high', 'High only (sev >= 4)'), ('medium', 'Medium & High (sev >= 3)'), ('all', 'All severities')], default='high', max_length=10)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel', to='api.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_name', models.CharField(default='restricted', max_length=100)),
                ('zone_type', models.CharField(choices=[('restricted', 'Restricted'), ('monitor', 'Monitor')], default='restricted', max_length=20)),
                ('polygon_points', models.JSONField(default=list, help_text='List of [x,y] normalised coords')),
                ('enabled', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='api.camera')),
            ],
            options={
                'unique_together': {('camera', 'zone_name')},
            },
        ),
    ]
