# Generated by Django 5.2.12 on 2026-03-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_camera_camera_type_camera_cooldown_s_camera_k_of_n_k_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(blank=True, default='', help_text="MediaMTX stream path for WebRTC/HLS (e.g. 'webcam')", max_length=200),
        ),
    ]
