# Generated by Django 5.2.7 on 2026-04-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_knownentityembedding_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='16-char hex hash of normalized URL for deduplication', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(condition=models.Q(('url_hash', ''), _negated=True), fields=('tenant', 'url_hash'), name='unique_url_per_tenant', violation_error_message='This camera URL is already registered in your account.'),
        ),
    ]
