# Generated by Django 5.2.7 on 2026-05-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_camera_url_hash_camera_unique_url_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamtxdesiredpath',
            name='last_applied_generation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediamtxdesiredpath',
            name='last_applied_payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mediamtxdesiredpath',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediamtxdesiredpath',
            name='camera',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediamtx_desired_path', to='api.camera'),
        ),
    ]
