# Generated by Django 5.2.12 on 2026-03-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_camera_stream_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ingress_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='ingress_rtmp_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='camera',
            name='ingress_stream_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='camera',
            name='livekit_room',
            field=models.CharField(blank=True, default='', help_text='LiveKit room name used for viewer playback', max_length=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='relay_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='camera',
            name='relay_status',
            field=models.CharField(choices=[('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('ERROR', 'Error')], default='STOPPED', max_length=16),
        ),
    ]
