# Generated by Django 5.2.7 on 2026-05-01 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mediamtx_stamp_convergence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('incident', 'user', 'channel')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['tenant', 'user', 'delivered_at', 'created_at'], name='api_alert_tenant__b5cfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='api_auditlo_tenant__f670b1_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'started_at'], name='api_inciden_tenant__8fc444_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'status', 'started_at'], name='api_inciden_tenant__8186ea_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'severity', 'started_at'], name='api_inciden_tenant__980827_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['camera', 'type', 'status', 'started_at'], name='api_inciden_camera__883bcc_idx'),
        ),
    ]
