# Generated by Django 5.2.7 on 2026-03-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_knownentity_camera_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_path',
            field=models.CharField(blank=True, default='', help_text='Stable camera stream identifier used for UI/AI mapping', max_length=200),
        ),
    ]
