# Generated by GitHub Copilot on 2026-03-25

import uuid
from django.db import migrations, models


def reconcile_public_id_column(apps, schema_editor):
    Invitation = apps.get_model("api", "Invitation")
    table = Invitation._meta.db_table
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        columns = {
            col.name
            for col in connection.introspection.get_table_description(cursor, table)
        }

    # Some environments already have this column from prior branch history.
    if "public_id" not in columns:
        field = models.UUIDField(null=True, editable=False)
        field.set_attributes_from_name("public_id")
        schema_editor.add_field(Invitation, field)

    # Backfill any null/empty values to satisfy runtime writes and uniqueness.
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id FROM {table} WHERE public_id IS NULL OR public_id = ''"
        )
        missing_ids = [row[0] for row in cursor.fetchall()]

    for row_id in missing_ids:
        Invitation.objects.filter(id=row_id).update(public_id=uuid.uuid4().hex)

    # Enforce uniqueness at DB level when possible.
    if connection.vendor == "sqlite":
        schema_editor.execute(
            f"CREATE UNIQUE INDEX IF NOT EXISTS {table}_public_id_uniq ON {table}(public_id)"
        )


def noop_reverse(apps, schema_editor):
    # Keep forward-only compatibility behavior.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_camera_stream_path"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    reconcile_public_id_column,
                    reverse_code=noop_reverse,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="invitation",
                    name="public_id",
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
