# Generated by Django 5.2.7 on 2026-03-30 04:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_profile_instant_notification_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instant_notification_types',
        ),
        migrations.AlterField(
            model_name='profile',
            name='instant_notification_levels',
            field=models.JSONField(blank=True, default=api.models.default_instant_notification_levels),
        ),
    ]
