# Generated by Django 5.2.7 on 2026-04-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_incidenteventreceipt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incidenteventreceipt',
            new_name='api_inciden_event_i_86c8b6_idx',
            old_name='api_inciden_event_i_idx',
        ),
        migrations.AddField(
            model_name='camera',
            name='source_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Optional TLS fingerprint for HTTPS IP cameras', max_length=256),
        ),
        migrations.AddField(
            model_name='camera',
            name='source_kind',
            field=models.CharField(blank=True, default='', help_text='Derived or explicit source kind (e.g., rtsp, mjpeg, hls)', max_length=50),
        ),
    ]
