# Generated by Django 5.2.7 on 2026-04-08 00:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_api_inciden_event_i_idx_api_inciden_event_i_86c8b6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='enabled_lanes',
            field=models.JSONField(blank=True, default=api.models.Camera._default_lanes, help_text="Active detection lanes (e.g. ['rt_detr', 'person_zone', 'fire_smoke_yolo'])"),
        ),
    ]
